#!/usr/bin/env php
<?php
/**
 * DASBiT
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE
 *
 * @category   DASBiT
 * @copyright  Copyright (c) 2010 Ben Scholzen (http://www.dasprids.de)
 * @license    New BSD License
 */

/**
 * @see \Dasbit\Loader
 */
require_once 'Dasbit/Loader.php';

// Register the autoloader
$loader = new \Dasbit\Loader(null, __DIR__);
$loader->register();

// Load the config
$hostname = 'chat.freenode.net';
$port     = 6667;
$nickname = 'DASBiT';
$username = 'dasbit';

// Configure the reactor and IRC client
$reactor   = new \Dasbit\Reactor();
$cli       = new \Dasbit\Cli();
$ircClient = new \Dasbit\Irc\Client($reactor, $cli, $hostname, $port, $nickname, $username);
$ircClient->connect();

// Start the reactor
$reactor->run();